version: "3.9" # optional since v1.27.0

services:
  myapp:
    image: myapp
    build: .
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
